language: python

sudo: required

python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - nightly

# command to install dependencies
before_install:
    - sudo apt-get update
    - sudo apt-get install liblapack-dev gfortran
    - sudo apt-get install glpk-utils libglpk-dev graphviz

install: pip install -r requirements.txt

# command to run tests
script:
    - make
    - py.test --doctest-modules --cov-report term-missing --cov=enzyme
after_success:
    - coveralls
